<?xml version="1.0" ?>

<!DOCTYPE carts [
  <!ELEMENT carts (Cart*)>
  <!ELEMENT Cart (booksincart, numberofitems, bookspecifics, cartlastupdated)>
  <!ELEMENT booksincart (#PCDATA)>
  <!ELEMENT bookspecifics (genresincart, authorsincart, publishersincart)>
  <!ELEMENT numberofitems (#PCDATA)>
  <!ELEMENT genresincart (#PCDATA)>
  <!ELEMENT authorsincart (#PCDATA)>
  <!ELEMENT publishersincart (#PCDATA)>
  <!ELEMENT cartlastupdated (#PCDATA)>
]>

<carts>
  <Cart>
    <booksincart>[Book1, Book2, Book3]</booksincart>
    <numberofitems>3</numberofitems>
    <bookspecifics>    
      <genresincart>[Action, SciFi, History]</genresincart>
      <authorsincart>["Jakub Blaszcykowski", "Artyom Fedorov", "Erich Bronstein"]</authorsincart>
      <publishersincart>["Dude Books", "Spy Books", "Smiley Books"]</publishersincart>
    </bookspecifics>
    <cartlastupdated>22/11/2021</cartlastupdated>
  </Cart>
</carts>