<?xml version="1.0" ?>

<!DOCTYPE authors [
  <!ELEMENT authors (Author*)>
  <!ELEMENT Author (personalinfo, genre, booklist, serieslist)>
  <!ELEMENT personalinfo (name, age, nationality)>
  <!ELEMENT name (firstname, lastname)>
  <!ELEMENT firstname (#PCDATA)>
  <!ELEMENT lastname (#PCDATA)>
  <!ELEMENT age (#PCDATA)>
  <!ELEMENT nationality (#PCDATA)>
  <!ELEMENT genre (#PCDATA)>
  <!ELEMENT booklist (#PCDATA)>
  <!ELEMENT serieslist (#PCDATA)>
]>

<authors>
  <Author>
    <personalinfo>
      <name>
        <firstname>Florian</firstname>
        <lastname>Theunier</lastname>
      </name>
      <age>29</age>
      <nationality>Belgian</nationality>
    </personalinfo>
    <genre>SciFi</genre>
    <booklist>
      [Book1, Book2, Book3]
    </booklist>
    <serieslist>
      ["Series1", "Series2", "Series3"]
    </serieslist>
  </Author>
  <Author>
    <personalinfo>
      <name>
        <firstname>Bo</firstname>
        <lastname>Hemmington</lastname>
      </name>
      <age>35</age>
      <nationality>Danish</nationality>
    </personalinfo>
    <genre>SciFi</genre>
    <booklist>
      [Book1, Book2, Book3]
    </booklist>
    <serieslist>
      ["Series1", "Series2", "Series3"]
    </serieslist>
  </Author>
</authors>